services:
  - type: web
    name: knowledge-base-search-engine
    runtime: python
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12
      - key: GOOGLE_API_KEY
        sync: false
      - key: LLM_PROVIDER
        value: google
      - key: LLM_MODEL
        value: models/gemini-2.0-flash
      - key: SIMILARITY_THRESHOLD
        value: 0.0
